### ISSUE TITLE
Request: Add count of entries per entity

### ISSUE THREAD

**Issue by dkho87** [aramlawi/EntityAccessCheck#2]
Would it be possible to have a count on the number of accessible entries per entity appended to each of the entries in the entity overview list? This would greatly improve overview of the entries that require more attention.

An example would be Administration.Account(1)

**Comment by aramlawi** [comment]
Good suggestion, but cannot do this as when we retrieve the entity names, we do not retrieve the objects, the objects are only retrieved when you click on the name. Doing this would require a lot of extra retrieves.
