### ISSUE TITLE
DataTables warning: table id=EntityOverviewTable - Cannot reinitialise DataTable

### ISSUE THREAD

**Issue by edwinvanelk** [aramlawi/EntityAccessCheck#6]
SecurityInspector widget is placed on a page (MyFirstModule.Home). When adding a show page button at the page to go to the same page (MyFirstModule.Home) error message is shown. Also when using the default navigation item with the home icon pointing to the same page (MyFirstModule.Home)

Error is shown only the first time after openening (or refreshing) the app in the browser:

==
localhost:7070 meldt het volgende

DataTables warning: table id=EntityOverviewTable - Cannot reinitialise DataTable. For more information about this error, please see http://datatables.net/tn/3
==

**Comment by aramlawi** [comment]
Fixed in v1.1
